services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=SuperAdmin123
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=SuperAdmin123
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=d5d2dd3f604f1c5b7136f8163538617ad49dd9777ebbb82a4614829e280b4d08
      - SERVER_HOST=0.0.0.0
      - XPACK_SECURITY_ENABLED=true
    ports:
      - "5601:5601"
    networks:
      - elk
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    command:
      [
        "redis-server",
        "--maxmemory",
        "200mb",
        "--maxmemory-policy",
        "allkeys-lru",
        "--appendonly",
        "no",
        "--save",
        "",
        "--requirepass",
        "SuperSecret123",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - elk
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:2.58.0
    container_name: redis-insight
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - elk
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    depends_on:
      - elasticsearch
      - redis
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=SuperAdmin123
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "5044:5044"
    volumes:
      # Mount the entire pipeline folder instead of individual files
      - ./pipeline/:/usr/share/logstash/pipeline/
      # Mount a clean config file
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - elk
    restart: unless-stopped

volumes:
  elasticsearch-data:
  redis-data:

networks:
  elk:
    driver: bridge
