input {
  beats {
    port => 5044
  }
}

filter {
  if [message] {
    json {
      source => "message"
      target => "parsed_message"
      skip_on_invalid_json => true
    }
  }

  mutate {
    remove_field => [
      "log.offset",
      "log.file.inode",
      "log.file.device_id",
      "ecs.version",
      "message"
    ]
  }

  
}

output {
  # Debug logs to console
  stdout { codec => rubydebug }

  # Send to Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "${ELASTIC_USERNAME}"
    password => "${ELASTIC_PASSWORD}"
    ecs_compatibility => "v8"
    ssl => false
    index => "%{[service]}-%{[api]}-%{+YYYY.MM.dd}"
  }
}
