input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    target => "parsed"
    skip_on_invalid_json => true
  }
}

output {
  # Send to Redis queue
  redis {
    host => "redis"
    port => 6379
    password => "SuperSecret123"
    data_type => "list"
    key => "filebeat"
    db => 0
    reconnect_interval => 5
  }

  # Debug on stdout
  stdout { codec => rubydebug }
}
